version: "3.9"
services:
  gateway:
    build: ./gateway
    ports:
      - "8080:8080"
    environment:
      DIAG_URL: http://diagnostics:8001
      CURR_URL: http://curriculum:8002
      PRED_URL: http://prediction:8003
      ING_URL:  http://ingestion:8004
      LOG_LEVEL: INFO
    depends_on:
      diagnostics:
        condition: service_healthy
      curriculum:
        condition: service_healthy
      prediction:
        condition: service_healthy
      ingestion:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://localhost:8080/health"]
      interval: 10s
      timeout: 3s
      retries: 5

  diagnostics:
    build: ./services/diagnostics
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://localhost:8001/health"]
      interval: 10s
      timeout: 3s
      retries: 5

  curriculum:
    build: ./services/curriculum
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://localhost:8002/health"]
      interval: 10s
      timeout: 3s
      retries: 5

  prediction:
    build: ./services/prediction
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://localhost:8003/health"]
      interval: 10s
      timeout: 3s
      retries: 5

  ingestion:
    build: ./services/ingestion
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://localhost:8004/health"]
      interval: 10s
      timeout: 3s
      retries: 5
